apiVersion: v1
kind: Service
metadata:
  name: sds-final-project-service
spec:
  selector:
    app: sds-final-project-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
